input {
  tcp {
    port => 9000
    codec => line
  }
}

output {
  sns {
    arn => "arn:aws:sns:us-east-1:000000000000:bench-topic"
    region => "us-east-1"
    endpoint => "http://localstack:4566"
  }
}
