devices:
  - id: 1
    name: tcp-bench
    type: tcp
    properties:
      address: "0.0.0.0"
      port: 9000
targets:
  - name: sns-target-bench
    type: amazonsns
    properties:
      endpoint: "http://localstack:4566"
      key: "test"
      secret: "test"
      region: "us-east-1"
      topic: "arn:aws:sns:us-east-1:000000000000:bench-topic"
routes:
  - name: tcp-to-sns-bench
    devices:
      - name: tcp-bench
    targets:
      - name: sns-target-bench
