package orchestrator

import (
	"fmt"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/VirtualMetric/PipeBench/internal/config"
)

// resolveGeneratorConnections picks the generator's parallel-connection
// count. An explicit non-zero value in case.yaml always wins. When unset
// (0), scale with the host's CPU count at 3× cores — enough parallelism
// to drive the subject's worker pools past their per-worker steady state
// without leaving large fractions of a multi-core box idle. On a 4-core
// dev box this produces 12 connections; on a 32-core box, 96; on a
// 192-core c6a.metal, 576.
//
// The intent is "what the host can drive", not "one connection per CPU" —
// the bench's subjects (vmetric/vector/etc.) typically run their own
// per-listener worker pools sized to NumCPU, so feeding them ~3× more
// connections than cores keeps those pools saturated rather than starved.
func resolveGeneratorConnections(explicit int) int {
	if explicit > 0 {
		return explicit
	}
	if n := runtime.NumCPU() * 3; n > 0 {
		return n
	}
	return 3
}

// configTemplateContext is the data exposed to a subject config rendered as a
// Go text/template. It carries only generic facts about the run — never a
// subject's tuning vocabulary — so a config adapts itself to the host
// (e.g. an OpenTelemetry source sets workers() to the CPU count).
type configTemplateContext struct {
	// CPUs is the host CPU count.
	CPUs int
}

// renderSubjectConfig renders the subject config at srcPath as a Go
// text/template when it contains template actions ("{{"), writing the result
// into tmpDir and returning the rendered file's path. Configs with no template
// actions, directory-form configs (e.g. cribl-stream), and missing paths are
// returned unchanged — so non-templated subjects, and the existing
// missing-path tolerance, are unaffected.
func renderSubjectConfig(srcPath, tmpDir string, ctx configTemplateContext) (string, error) {
	info, err := os.Stat(srcPath)
	if err != nil || info.IsDir() {
		return srcPath, nil
	}
	raw, err := os.ReadFile(srcPath)
	if err != nil {
		return "", err
	}
	if !strings.Contains(string(raw), "{{") {
		return srcPath, nil
	}
	tmpl, err := template.New(filepath.Base(srcPath)).Parse(string(raw))
	if err != nil {
		return "", fmt.Errorf("parsing config template %s: %w", srcPath, err)
	}
	outPath := filepath.Join(tmpDir, filepath.Base(srcPath))
	f, err := os.Create(outPath)
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tmpl.Execute(f, ctx); err != nil {
		return "", fmt.Errorf("rendering config template %s: %w", srcPath, err)
	}
	return outPath, nil
}

const composeTemplate = `# Auto-generated by harness — do not edit
networks:
  bench:
    driver: bridge

volumes:
  shared-data:

services:

  subject:
    image: "{{ .SubjectImage }}"
    container_name: "{{ .SubjectContainer }}"
    networks: [bench]
{{- if or .KafkaEnabled .AWSEnabled .AzureEnabled .VaultEnabled .MinioEnabled }}
    depends_on:
{{- if .KafkaGSSAPIEnabled }}
      kafka-init:
        condition: service_completed_successfully
{{- else if .KafkaEnabled }}
      redpanda-init:
        condition: service_completed_successfully
{{- end }}
{{- if .VaultEnabled }}
      vault-init:
        condition: service_completed_successfully
{{- end }}
{{- if .AWSEnabled }}
      localstack:
        condition: service_healthy
{{- end }}
{{- if .AzureEnabled }}
      azure-init:
        condition: service_completed_successfully
{{- end }}
{{- if .MinioEnabled }}
      minio-init:
        condition: service_completed_successfully
{{- end }}
{{- end }}
    volumes:
      - "{{ .ConfigSrc }}:{{ .ConfigDst }}{{ .ConfigMountOpts }}"
      - "{{ .TmpDir }}:/results"
{{- if .UseSharedData }}
      - "shared-data:/data"
{{- end }}
{{- if .TLSCertsHost }}
      - "{{ .TLSCertsHost }}:/certs:ro"
{{- if .SubjectCertDir }}
      - "{{ .TLSCertsHost }}:{{ .SubjectCertDir }}:ro"
{{- end }}
{{- end }}
{{- if .KrbHostDir }}
      - "{{ .KrbHostDir }}:/krb5:ro"
{{- end }}
{{- if .VaultEnabled }}
{{- if .SubjectVaultDir }}
      - "{{ .VaultTLSHost }}:{{ .SubjectVaultDir }}:ro"
{{- else }}
      - "{{ .VaultTLSHost }}:/vault-tls:ro"
{{- end }}
{{- end }}
{{- if .SubjectUser }}
    user: "{{ .SubjectUser }}"
{{- end }}
{{- if .SubjectEntrypoint }}
    entrypoint: {{ .SubjectEntrypoint }}
{{- end }}
{{- if .SubjectCmd }}
    command: {{ .SubjectCmd }}
{{- end }}
{{- if .SubjectEnv }}
    environment:
{{- range $k, $v := .SubjectEnv }}
      {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
{{- if .HasResourceLimits }}
    deploy:
      resources:
        limits:
          cpus: "{{ .CPULimit }}"
          memory: "{{ .MemLimit }}"
        reservations:
          cpus: "{{ .CPULimit }}"
          memory: "{{ .MemLimit }}"
{{- end }}
    restart: "no"

{{- if .Generators }}
{{- range .Generators }}

  generator-{{ .ID }}:
    image: "{{ $.GeneratorImage }}"
    container_name: "bench-generator-{{ .ID }}"
    networks: [bench]
    depends_on:
      subject:
        condition: service_started
{{- if not $.DeferReceiver }}
{{- range $.Receivers }}
      receiver-{{ .ID }}:
        condition: service_started
{{- end }}
{{- end }}
{{- if $.AWSEnabled }}
      localstack:
        condition: service_healthy
{{- end }}
{{- if $.AzureEnabled }}
      azure-init:
        condition: service_completed_successfully
{{- end }}
{{- if $.MinioEnabled }}
      minio-init:
        condition: service_completed_successfully
{{- end }}
{{- if or $.UseSharedData $.TLSCertsHost .SampleFileHost }}
    volumes:
{{- if $.UseSharedData }}
      - "shared-data:/data"
{{- end }}
{{- if $.TLSCertsHost }}
      - "{{ $.TLSCertsHost }}:/certs:ro"
{{- end }}
{{- if .SampleFileHost }}
      - "{{ .SampleFileHost }}:{{ .SampleFileDst }}:ro"
{{- end }}
{{- end }}
{{- if $.UseSharedData }}
    user: "0:0"
{{- end }}
    environment:
      GENERATOR_ID: "{{ .ID }}"
      GENERATOR_MODE: "{{ .Mode }}"
      GENERATOR_TARGET: "{{ .Target }}"
      GENERATOR_RATE: "{{ .Rate }}"
      GENERATOR_DURATION: "{{ $.GenDuration }}"
      GENERATOR_LINE_SIZE: "{{ .LineSize }}"
      GENERATOR_FORMAT: "{{ .Format }}"
      GENERATOR_WARMUP: "{{ $.GenWarmup }}"
      GENERATOR_SEQUENCED: "{{ $.GenSequenced }}"
      GENERATOR_CONNECTIONS: "{{ .Connections }}"
      GENERATOR_CONN_OFFSET: "{{ .ConnOffset }}"
{{- if .TotalLines }}
      GENERATOR_TOTAL_LINES: "{{ .TotalLines }}"
{{- end }}
{{- if .SampleFile }}
      GENERATOR_SAMPLE_FILE: "{{ .SampleFile }}"
{{- end }}
{{- if .RewriteTimestamp }}
      GENERATOR_REWRITE_TIMESTAMP: "true"
{{- end }}
{{- if .TLSEnabled }}
      GENERATOR_TLS: "true"
{{- if .TLSCert }}
      GENERATOR_TLS_CERT: "{{ .TLSCert }}"
{{- end }}
{{- if .TLSKey }}
      GENERATOR_TLS_KEY: "{{ .TLSKey }}"
{{- end }}
{{- if .TLSCA }}
      GENERATOR_TLS_CA: "{{ .TLSCA }}"
{{- end }}
      GENERATOR_TLS_INSECURE: "{{ .TLSInsecure }}"
{{- if .TLSMinVersion }}
      GENERATOR_TLS_MIN_VERSION: "{{ .TLSMinVersion }}"
{{- end }}
{{- end }}
{{- range $k, $v := .Env }}
      {{ $k }}: "{{ $v }}"
{{- end }}
    restart: "no"
{{- end }}
{{- else if .EmitGenerator }}

  generator:
    image: "{{ .GeneratorImage }}"
    container_name: "bench-generator"
    networks: [bench]
{{- if and (eq .GenMode "kafka") .KafkaGSSAPIEnabled }}
    depends_on:
      kafka-init:
        condition: service_completed_successfully
{{- else if and (eq .GenMode "kafka") .KafkaEnabled }}
    depends_on:
      redpanda-init:
        condition: service_completed_successfully
{{- else }}
    depends_on:
      subject:
        condition: service_started
{{- if and (not .DeferReceiver) (not .VerifierEnabled) }}
      receiver:
        condition: service_started
{{- end }}
{{- if .AWSEnabled }}
      localstack:
        condition: service_healthy
{{- end }}
{{- if .AzureEnabled }}
      azure-init:
        condition: service_completed_successfully
{{- end }}
{{- if .MinioEnabled }}
      minio-init:
        condition: service_completed_successfully
{{- end }}
{{- end }}
{{- if or .UseSharedData .TLSCertsHost .GenSampleFileHost }}
    volumes:
{{- if .UseSharedData }}
      - "shared-data:/data"
{{- end }}
{{- if .TLSCertsHost }}
      - "{{ .TLSCertsHost }}:/certs:ro"
{{- end }}
{{- if .GenSampleFileHost }}
      - "{{ .GenSampleFileHost }}:{{ .GenSampleFileDst }}:ro"
{{- end }}
{{- end }}
{{- if .UseSharedData }}
    # File-mode tests need the generator to create /data/input.log on the
    # shared volume, which is initialized as root:root 0755. The image's
    # default uid 10001 cannot write there, so override to root for these
    # runs. TCP/HTTP/OTLP/netflow runs leave the hardened uid in place.
    user: "0:0"
{{- end }}
    environment:
      GENERATOR_MODE: "{{ .GenMode }}"
      GENERATOR_TARGET: "{{ .GenTarget }}"
      GENERATOR_RATE: "{{ .GenRate }}"
      GENERATOR_DURATION: "{{ .GenDuration }}"
      GENERATOR_LINE_SIZE: "{{ .GenLineSize }}"
      GENERATOR_FORMAT: "{{ .GenFormat }}"
      GENERATOR_WARMUP: "{{ .GenWarmup }}"
      GENERATOR_SEQUENCED: "{{ .GenSequenced }}"
      GENERATOR_CONNECTIONS: "{{ .GenConnections }}"
{{- if .GenTotalLines }}
      GENERATOR_TOTAL_LINES: "{{ .GenTotalLines }}"
{{- end }}
{{- if .GenSampleFile }}
      GENERATOR_SAMPLE_FILE: "{{ .GenSampleFile }}"
{{- end }}
{{- if .GenRewriteTimestamp }}
      GENERATOR_REWRITE_TIMESTAMP: "true"
{{- end }}
{{- if .KafkaEnabled }}
      GENERATOR_KAFKA_TOPIC: "{{ .KafkaTopic }}"
      GENERATOR_KAFKA_BATCH: "{{ .GenKafkaBatch }}"
{{- if .KafkaSASLEnabled }}
      GENERATOR_KAFKA_SASL: "{{ .KafkaSASLMechanism }}"
      GENERATOR_KAFKA_USER: "{{ .KafkaSASLUser }}"
      GENERATOR_KAFKA_PASSWORD: "{{ .KafkaSASLPassword }}"
{{- end }}
{{- if .KafkaTLSEnabled }}
      GENERATOR_KAFKA_TLS: "true"
{{- end }}
{{- end }}
{{- if .GenRotateMode }}
      GENERATOR_ROTATE_MODE: "{{ .GenRotateMode }}"
      GENERATOR_ROTATE_AT: "{{ .GenRotateAt }}"
      GENERATOR_ROTATE_QUIESCE: "{{ .GenRotateQuiesce }}"
      GENERATOR_ROTATE_ARCHIVE_SUFFIX: "{{ .GenRotateSuffix }}"
{{- end }}
{{- if .GenTLSEnabled }}
      GENERATOR_TLS: "true"
{{- if .GenTLSCert }}
      GENERATOR_TLS_CERT: "{{ .GenTLSCert }}"
{{- end }}
{{- if .GenTLSKey }}
      GENERATOR_TLS_KEY: "{{ .GenTLSKey }}"
{{- end }}
{{- if .GenTLSCA }}
      GENERATOR_TLS_CA: "{{ .GenTLSCA }}"
{{- end }}
      GENERATOR_TLS_INSECURE: "{{ .GenTLSInsecure }}"
{{- if .GenTLSMinVersion }}
      GENERATOR_TLS_MIN_VERSION: "{{ .GenTLSMinVersion }}"
{{- end }}
{{- end }}
{{- range $k, $v := .GenEnv }}
      {{ $k }}: "{{ $v }}"
{{- end }}
    restart: "no"
{{- end }}

{{- if .Receivers }}
{{- range .Receivers }}

  receiver-{{ .ID }}:
    image: "{{ $.ReceiverImage }}"
    container_name: "bench-receiver-{{ .ID }}"
    networks: [bench]
{{- if or .AWSDep .AzureDep .MinioDep }}
    depends_on:
{{- if .AWSDep }}
      localstack:
        condition: service_healthy
{{- end }}
{{- if .AzureDep }}
      azure-init:
        condition: service_completed_successfully
{{- end }}
{{- if .MinioDep }}
      minio-init:
        condition: service_completed_successfully
{{- end }}
{{- end }}
    ports:
      - "{{ .HostPort }}:9090"
    environment:
      RECEIVER_MODE: "{{ .Mode }}"
      RECEIVER_LISTEN: "{{ .Listen }}"
      RECEIVER_METRICS_PORT: "9090"
      RECEIVER_VALIDATE_DEDUP: "{{ $.RecvValidateDedup }}"
      RECEIVER_VALIDATE_CONTENT: "{{ $.RecvValidateContent }}"
{{- if $.RecvRequiredSubstring }}
      RECEIVER_REQUIRED_SUBSTRING: "{{ $.RecvRequiredSubstring }}"
{{- end }}
{{- if $.RecvValidateJSON }}
      RECEIVER_VALIDATE_JSON: "true"
{{- end }}
{{- if $.RecvRecordArrival }}
      RECEIVER_RECORD_ARRIVAL_TIMES: "true"
{{- end }}
{{- range $k, $v := .Env }}
      {{ $k }}: "{{ $v }}"
{{- end }}
    restart: "no"
{{- end }}
{{- else if not .VerifierEnabled }}

  receiver:
    image: "{{ .ReceiverImage }}"
    container_name: "bench-receiver"
    networks: [bench]
{{- if or .RecvAWSDep .RecvAzureDep .RecvMinioDep }}
    depends_on:
{{- if .RecvAWSDep }}
      localstack:
        condition: service_healthy
{{- end }}
{{- if .RecvAzureDep }}
      azure-init:
        condition: service_completed_successfully
{{- end }}
{{- if .RecvMinioDep }}
      minio-init:
        condition: service_completed_successfully
{{- end }}
{{- end }}
    ports:
      - "{{ .ReceiverHostPort }}:9090"
    environment:
      RECEIVER_MODE: "{{ .RecvMode }}"
      RECEIVER_LISTEN: "{{ .RecvListen }}"
      RECEIVER_METRICS_PORT: "9090"
      RECEIVER_VALIDATE_DEDUP: "{{ .RecvValidateDedup }}"
      RECEIVER_VALIDATE_CONTENT: "{{ .RecvValidateContent }}"
{{- if .RecvExpectedLines }}
      RECEIVER_EXPECTED_LINES: "{{ .RecvExpectedLines }}"
{{- end }}
{{- if .RecvRequiredSubstring }}
      RECEIVER_REQUIRED_SUBSTRING: "{{ .RecvRequiredSubstring }}"
{{- end }}
{{- if .RecvValidateJSON }}
      RECEIVER_VALIDATE_JSON: "true"
{{- end }}
{{- if .RecvRecordArrival }}
      RECEIVER_RECORD_ARRIVAL_TIMES: "true"
{{- end }}
{{- range $k, $v := .RecvEnv }}
      {{ $k }}: "{{ $v }}"
{{- end }}
    restart: "no"
{{- end }}

  collector:
    image: "{{ .CollectorImage }}"
    container_name: "bench-collector"
    networks: [bench]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ .TmpDir }}:/results"
{{- if .DockerSocketGID }}
    group_add:
      - "{{ .DockerSocketGID }}"
{{- else }}
    # Docker Desktop (Windows/macOS) doesn't expose a numeric gid owning
    # /var/run/docker.sock that we can map onto the host filesystem, so
    # the hardened uid 10001 collector image can't read the socket. Fall
    # back to uid 0 inside the container — this is a measurement sidecar
    # reading its own host's Docker stats API, not exposed to traffic.
    user: "0:0"
{{- end }}
    environment:
      COLLECTOR_TARGET_CONTAINER: "{{ .SubjectContainer }}"
      COLLECTOR_INTERVAL_SECS: "1"
      COLLECTOR_OUTPUT: "/results/metrics.csv"
    restart: "no"
{{- if .VerifierEnabled }}

  # One-shot DuckDB verifier under the compose profile "verify", so the
  # initial up skips it; the runner starts it (UpServices) after the generator
  # exits. It reads the subject's {{ .VerifierFormat }} objects from the S3
  # emulator via httpfs, waits for the bucket to settle, then asserts row count
  # / duplicates / NULL payloads and writes /results/verdict.json.
  verifier:
    image: "{{ .VerifierImage }}"
    container_name: "bench-verifier"
    networks: [bench]
    profiles: ["verify"]
    volumes:
      - "{{ .TmpDir }}:/results"
    user: "0:0"
    environment:
      VERIFIER_S3_BUCKET: "{{ .VerifierBucket }}"
{{- if .VerifierPrefix }}
      VERIFIER_S3_PREFIX: "{{ .VerifierPrefix }}"
{{- end }}
      VERIFIER_OBJECT_FORMAT: "{{ .VerifierFormat }}"
      VERIFIER_EXPECTED_LINES: "{{ .VerifierExpected }}"
      VERIFIER_ALLOW_OVERDELIVERY: "{{ .VerifierAllowOverDel }}"
      VERIFIER_QUIET_WINDOW: "{{ .VerifierQuietWindow }}"
      VERIFIER_TIMEOUT: "{{ .VerifierTimeout }}"
      VERIFIER_MSG_FIELD: "{{ .VerifierMsgField }}"
{{- if .VerifierNullFields }}
      VERIFIER_NULL_FIELDS: "{{ .VerifierNullFields }}"
{{- end }}
{{- range $k, $v := .VerifierEnv }}
      {{ $k }}: "{{ $v }}"
{{- end }}
    restart: "no"
{{- end }}
{{- range .Endpoints }}

  {{ .Name }}:
    image: "{{ .Image }}"
    container_name: "bench-{{ .Name }}"
    hostname: "{{ .Name }}"
    networks: [bench]
{{- if .Command }}
    command: {{ .Command }}
{{- end }}
{{- if .Env }}
    environment:
{{- range $k, $v := .Env }}
      {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
    restart: "no"
{{- end }}
{{- if .KafkaGSSAPIEnabled }}

  # MIT Kerberos KDC: creates the realm + broker SPN + client principal and
  # exports their keytabs into the shared /krb5 dir at boot (see
  # internal/orchestrator/kerberos.go). Healthy once the keytabs exist.
  kdc:
    image: "{{ .KDCImage }}"
    container_name: "bench-kdc"
    hostname: "kdc"
    networks: [bench]
    # krb5kdc runs non-root (see containers/kdc/Dockerfile) yet binds privileged
    # port 88. Docker defaults this namespaced sysctl to 0 in the container's net
    # namespace, but set it explicitly so the bind never silently fails if a host
    # or runtime ships a different default.
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    volumes:
      - "{{ .KrbHostDir }}:/krb5"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "{{ .KerberosInitCmd }}"
    healthcheck:
      test: ["CMD-SHELL", "test -f /krb5/.ready"]
      interval: 2s
      timeout: 5s
      retries: 40
      start_period: 2s
    restart: "no"

  # Apache Kafka (KRaft) with a dual listener: PLAINTEXT for the generator +
  # topic-init, SASL_PLAINTEXT/GSSAPI for the subject (Redpanda can't serve
  # Kerberos without an enterprise license). The broker authenticates with its
  # keytab via inline JAAS.
  kafka:
    image: "{{ .KafkaImage }}"
    container_name: "bench-kafka"
    hostname: "kafka"
    networks: [bench]
    depends_on:
      kdc:
        condition: service_healthy
    volumes:
      - "{{ .KrbHostDir }}:/krb5:ro"
    environment:
      CLUSTER_ID: "{{ .KafkaClusterID }}"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,SASL_PLAINTEXT://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,SASL_PLAINTEXT://kafka:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_SASL_ENABLED_MECHANISMS: "GSSAPI"
      KAFKA_SASL_KERBEROS_SERVICE_NAME: "{{ .KerberosServiceName }}"
      # Double underscore (SASL__PLAINTEXT) encodes the literal "_" in the
      # listener name sasl_plaintext — the cp-kafka env→property converter maps
      # "__"→"_" and "_"→"." , so single underscores here would wrongly yield
      # listener.name.sasl.plaintext.* and the JAAS entry is never found.
      KAFKA_LISTENER_NAME_SASL__PLAINTEXT_GSSAPI_SASL_JAAS_CONFIG: 'com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/krb5/broker.keytab" principal="{{ .KerberosServiceName }}/kafka@{{ .KerberosRealm }}";'
      KAFKA_OPTS: "-Djava.security.krb5.conf=/krb5/krb5.conf"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 40
      start_period: 10s
    restart: "no"

  # One-shot: create the topic over the PLAINTEXT listener (the generator also
  # produces over PLAINTEXT). Generator + subject gate on this completing.
  kafka-init:
    image: "{{ .KafkaImage }}"
    container_name: "bench-kafka-init"
    networks: [bench]
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic {{ .KafkaTopic }} --partitions {{ .KafkaPartitions }} --replication-factor 1"
    restart: "no"
{{- else if .KafkaEnabled }}

  redpanda:
    image: "{{ .KafkaImage }}"
    container_name: "bench-redpanda"
    hostname: "redpanda"
    networks: [bench]
{{- if .KafkaTLSEnabled }}
    volumes:
      - "{{ .TLSCertsHost }}:/certs:ro"
{{- end }}
    command:
      - redpanda
      - start
      - "--mode"
      - "dev-container"
      - "--smp"
      - "{{ .KafkaSMP }}"
      - "--memory"
      - "{{ .KafkaMemory }}"
{{- if .KafkaAuthEnabled }}
      # Named listener "internal" so the TLS config can match it by name. SASL
      # and/or mTLS is applied per-listener; topics auto-create on first
      # produce (no authenticated topic-init needed).
      - "--kafka-addr"
      - "internal://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "internal://redpanda:9092"
      - "--set"
      - "redpanda.auto_create_topics_enabled=true"
      - "--set"
      - "redpanda.kafka_api[0].authentication_method={{ .KafkaAuthMethod }}"
{{- if .KafkaSASLEnabled }}
      - "--set"
      - "redpanda.enable_sasl=true"
      - "--set"
      - "redpanda.superusers=['{{ .KafkaSASLUser }}']"
      # Enable PLAIN alongside SCRAM (Redpanda defaults to SCRAM-only and
      # rejects PLAIN-only). The mechanism name is "SCRAM" (it covers both
      # SCRAM-SHA-256 and SCRAM-SHA-512) — the per-variant names are NOT valid
      # sasl_mechanisms values. PLAIN validates against the SCRAM-SHA-256
      # credential the user is bootstrapped with.
      - "--set"
      - "redpanda.sasl_mechanisms=['SCRAM','PLAIN']"
{{- end }}
{{- if .KafkaTLSEnabled }}
      - "--set"
      - 'redpanda.kafka_api_tls=[{"name":"internal","enabled":true,"cert_file":"/certs/server.crt","key_file":"/certs/server.key","truststore_file":"/certs/ca.crt","require_client_auth":{{ .KafkaRequireClientAuth }}}]'
{{- end }}
{{- else }}
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://redpanda:9092"
      - "--set"
      - "redpanda.auto_create_topics_enabled=true"
{{- end }}
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 3s
      timeout: 5s
      retries: 30
      start_period: 5s
    restart: "no"

  # One-shot: wait for the broker, then either create the topic (no-auth path)
  # or bootstrap the SASL user over the unauthenticated admin API (auth path,
  # where the topic auto-creates on first produce). Generator and subject gate
  # on this completing.
  redpanda-init:
    image: "{{ .KafkaImage }}"
    container_name: "bench-redpanda-init"
    networks: [bench]
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
{{- if .KafkaSASLEnabled }}
      # A Redpanda user can be created only once, so create it under the single
      # mechanism the case uses (SASL/PLAIN authenticates against SCRAM-SHA-256).
      - "rpk security user create {{ .KafkaSASLUser }} -p {{ .KafkaSASLPassword }} --mechanism {{ .KafkaBootstrapMechanism }} --api-urls redpanda:9644; echo redpanda sasl init complete"
{{- else if .KafkaAuthEnabled }}
      # Pure echo — the mTLS path has no user to bootstrap and the topic
      # auto-creates on first produce; this just satisfies the one-shot gate.
      - "echo 'redpanda mtls init complete (topic auto-creates on first produce)'"
{{- else }}
      - "rpk topic create {{ .KafkaTopic }} -p {{ .KafkaPartitions }} --brokers redpanda:9092 || rpk topic describe {{ .KafkaTopic }} --brokers redpanda:9092"
{{- end }}
    restart: "no"
{{- end }}
{{- if .VaultEnabled }}

  vault:
    image: "{{ .VaultImage }}"
    container_name: "bench-vault"
    hostname: "vault"
    networks: [bench]
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "{{ .VaultToken }}"
    command:
      - server
      - "-dev"
      - "-dev-tls"
      - "-dev-tls-cert-dir=/vault/tls"
      - "-dev-tls-san=vault"
      - "-dev-listen-address=0.0.0.0:8200"
    volumes:
      - "{{ .VaultTLSHost }}:/vault/tls"
    # -tls-skip-verify is a liveness probe choice, not a trust decision: the
    # check races the dev server writing its own cert dir at startup. Full
    # chain verification happens in vault-init (VAULT_CACERT) and the subject.
    healthcheck:
      test: ["CMD", "vault", "status", "-address=https://127.0.0.1:8200", "-tls-skip-verify"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 3s
    restart: "no"

  # One-shot: seed each declared secret from its mounted JSON file, then
  # exit 0. The subject gates on this completing so config-load-time
  # $secret resolution never races the seeding.
  vault-init:
    image: "{{ .VaultImage }}"
    container_name: "bench-vault-init"
    networks: [bench]
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: "https://vault:8200"
      VAULT_CACERT: "/vault/tls/vault-ca.pem"
      VAULT_TOKEN: "{{ .VaultToken }}"
    volumes:
      - "{{ .VaultTLSHost }}:/vault/tls:ro"
      - "{{ .VaultSecretsHost }}:/vault-secrets:ro"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "{{ .VaultInitCmd }}"
{{- end }}
{{- if .AWSEnabled }}

  localstack:
    image: "{{ .AWSImage }}"
    container_name: "bench-localstack"
    hostname: "localstack"
    networks: [bench]
    # Unlimited-rate S3 cases push hundreds of thousands of objects per
    # minute; LocalStack's S3 keeps temp files per in-flight object and
    # dies with EMFILE at the default container nofile limit.
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      SERVICES: "{{ .AWSServices }}"
      AWS_DEFAULT_REGION: "{{ .AWSRegion }}"
      EAGER_SERVICE_LOADING: "1"
      # Generated resource URLs (GetQueueUrl etc.) default to
      # localhost.localstack.cloud, which doesn't resolve on the bench
      # network — SDKs that follow those URLs (logstash's SQS output)
      # then connect nowhere. Pin URLs to the compose hostname, and use
      # path-style queue URLs (domain style would prepend sqs.<region>.,
      # which is not a resolvable alias here).
      LOCALSTACK_HOST: "localstack:4566"
      SQS_ENDPOINT_STRATEGY: "path"
    volumes:
      - "{{ .AWSInitHost }}:/etc/localstack/init/ready.d/init-bench.sh:ro"
    healthcheck:
      # Init hooks in ready.d run before "completed" flips true, so this
      # gates BOTH emulator readiness and bench resource creation.
      test: ["CMD-SHELL", "curl -sf localhost:4566/_localstack/init/ready | grep -q '\"completed\": true'"]
      interval: 3s
      timeout: 5s
      retries: 40
      start_period: 10s
    restart: "no"
{{- end }}
{{- if .AzureEnabled }}

  azurite:
    image: "{{ .AzureImage }}"
    container_name: "bench-azurite"
    hostname: "azurite"
    networks: [bench]
    command: ["azurite", "--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--inMemoryPersistence", "--skipApiVersionCheck"]
    restart: "no"

  # One-shot: retry container/queue creation until Azurite answers, then
  # exit 0. Reuses the bench-receiver image (it links the Azure SDK) so no
  # azure-cli image pull is needed — exact redpanda-init semantics.
  azure-init:
    image: "{{ .ReceiverImage }}"
    container_name: "bench-azure-init"
    networks: [bench]
    depends_on:
      - azurite
    environment:
      RECEIVER_MODE: "azure_init"
      AZURE_STORAGE_CONNECTION_STRING: "{{ .AzureConnString }}"
      AZURE_INIT_CONTAINERS: "{{ .AzureInitContainers }}"
    restart: "no"
{{- end }}
{{- if .MinioEnabled }}

  # MinIO is a multi-core, Go S3-compatible store — no Docker cpu limit so it
  # uses every host core (unlike LocalStack's GIL-bound single-core S3).
  minio:
    image: "{{ .MinioImage }}"
    container_name: "bench-minio"
    hostname: "minio"
    networks: [bench]
    command: ["server", "/data"]
    environment:
      MINIO_ROOT_USER: "{{ .MinioRootUser }}"
      MINIO_ROOT_PASSWORD: "{{ .MinioRootPassword }}"
    restart: "no"

  # One-shot: create the declared buckets over the S3 API, retrying until
  # MinIO answers, then exit 0. Reuses the bench-receiver image (it links the
  # AWS S3 SDK) so no mc client image is pulled — the azure-init pattern.
  minio-init:
    image: "{{ .ReceiverImage }}"
    container_name: "bench-minio-init"
    networks: [bench]
    depends_on:
      - minio
    environment:
      RECEIVER_MODE: "minio_init"
      RECEIVER_S3_ENDPOINT: "{{ .MinioEndpoint }}"
      MINIO_INIT_BUCKETS: "{{ .MinioInitBuckets }}"
      AWS_ACCESS_KEY_ID: "{{ .MinioRootUser }}"
      AWS_SECRET_ACCESS_KEY: "{{ .MinioRootPassword }}"
      AWS_REGION: "us-east-1"
      AWS_EC2_METADATA_DISABLED: "true"
    restart: "no"
{{- end }}
`

// RunConfig holds parameters for a single test run.
type RunConfig struct {
	TestCase         *config.TestCase
	Subject          config.Subject
	ConfigName       string
	ConfigSrcPath    string // absolute path to the subject config file on host
	CaseDir          string // absolute path to the case directory on host (locates generator sample_file, etc.)
	TmpDir           string // temp dir for this run
	GeneratorImage   string
	ReceiverImage    string
	CollectorImage   string
	VerifierImage    string // DuckDB verifier image (verifier cases only)
	ReceiverHostPort int    // base host port; in multi-receiver mode, +N for receiver N
	ExtraSubjectEnv  map[string]string
	CPULimit         string // e.g. "1", "4" — number of cores for subject
	MemLimit         string // e.g. "1g", "16g" — memory limit for subject
	DockerSocketGID  string // numeric gid owning /var/run/docker.sock; passed to collector via group_add so a non-root image can still read the socket
	// TLSCertsHost, when non-empty, is the absolute host path holding
	// ca.crt + server.crt/key + client.crt/key for a TLS-enabled run.
	// The harness writes the certs there before `docker compose up`; the
	// path is bind-mounted into the subject and every TLS-using generator
	// at /certs:ro.
	TLSCertsHost string
	// VaultTLSHost / VaultSecretsHost / VaultSeeds are the host paths and
	// seed list provisioned by PrepareVault for a `vault:`-enabled case.
	// NewComposeRunner populates them when empty; tests may set them
	// directly to render a compose file without touching the filesystem.
	VaultTLSHost     string
	VaultSecretsHost string
	VaultSeeds       []VaultSeed
	// KrbHostDir / KerberosInitCmd are provisioned by PrepareKerberos for a
	// `kafka.auth.mechanism: gssapi` case. NewComposeRunner populates them when
	// empty; tests may set them directly to render without touching the KDC.
	KrbHostDir      string
	KerberosInitCmd string
}

// ComposeRunner manages a docker compose lifecycle for one test run.
type ComposeRunner struct {
	cfg         RunConfig
	composeFile string

	// genServices / recvServices cache the compose service names so the
	// runner can stop/inspect them without re-deriving from the case.
	genServices    []string
	genContainers  []string
	recvServices   []string
	recvContainers []string
	// recvHostPorts maps receiver id → host port for the /metrics endpoint.
	recvHostPorts map[string]int
}

// Ensure ComposeRunner implements Orchestrator.
var _ Orchestrator = (*ComposeRunner)(nil)

// NewComposeRunner creates a ComposeRunner and writes the compose file.
func NewComposeRunner(cfg RunConfig) (*ComposeRunner, error) {
	if err := os.MkdirAll(cfg.TmpDir, 0o755); err != nil {
		return nil, err
	}

	if cfg.DockerSocketGID == "" {
		cfg.DockerSocketGID = dockerSocketGID()
	}

	// Vault topology prep lives here (not in the runner) so every RunConfig
	// construction site — including the persistence/restart flows — gets it
	// from the single place all of them already pass through.
	if cfg.TestCase.UsesVault() && cfg.VaultTLSHost == "" {
		vp, err := PrepareVault(cfg.TmpDir, cfg.TestCase.Vault)
		if err != nil {
			return nil, fmt.Errorf("preparing vault topology: %w", err)
		}
		cfg.VaultTLSHost, cfg.VaultSecretsHost, cfg.VaultSeeds = vp.TLSDir, vp.SecretsDir, vp.Seeds
	}

	// Kerberos topology prep, same pattern as Vault: a gssapi case needs the
	// KDC bootstrap command + the shared krb5 dir before the compose file is
	// rendered.
	if cfg.TestCase.Kafka != nil && cfg.TestCase.Kafka.UsesGSSAPI() && cfg.KrbHostDir == "" {
		kp, err := PrepareKerberos(cfg.TmpDir, cfg.TestCase.Kafka)
		if err != nil {
			return nil, fmt.Errorf("preparing kerberos topology: %w", err)
		}
		cfg.KrbHostDir, cfg.KerberosInitCmd = kp.Dir, kp.InitCmd
	}

	composeFile := filepath.Join(cfg.TmpDir, "docker-compose.yaml")
	if err := writeCompose(composeFile, cfg); err != nil {
		return nil, err
	}

	cr := &ComposeRunner{cfg: cfg, composeFile: composeFile}
	cr.populateServiceNames()
	return cr, nil
}

// populateServiceNames fills in the cached generator/receiver service and
// container names so subsequent operations don't re-walk the case.
func (r *ComposeRunner) populateServiceNames() {
	tc := r.cfg.TestCase
	if tc.MultiGenerator() {
		for _, g := range tc.Generators {
			r.genServices = append(r.genServices, "generator-"+g.ID)
			r.genContainers = append(r.genContainers, "bench-generator-"+g.ID)
		}
	} else if tc.HasGenerator() {
		r.genServices = []string{"generator"}
		r.genContainers = []string{"bench-generator"}
	}
	// else: no generator configured — leave the lists empty so nothing waits
	// on or queries a generator container that the compose never renders.
	r.recvHostPorts = map[string]int{}
	// Verifier cases render no receiver service (the subject's sink is S3), so
	// leave the receiver metadata empty rather than advertising a receiver that
	// doesn't exist — ReceiverMetricsPort(s) must not point at a phantom port.
	if tc.UsesVerifier() {
		return
	}
	if tc.MultiReceiver() {
		for i, rc := range tc.Receivers {
			r.recvServices = append(r.recvServices, "receiver-"+rc.ID)
			r.recvContainers = append(r.recvContainers, "bench-receiver-"+rc.ID)
			r.recvHostPorts[rc.ID] = r.cfg.ReceiverHostPort + i
		}
	} else {
		r.recvServices = []string{"receiver"}
		r.recvContainers = []string{"bench-receiver"}
		r.recvHostPorts["default"] = r.cfg.ReceiverHostPort
	}
}

// dockerSocketGID is defined per-platform (docker_socket_gid_*.go). It returns
// the numeric gid owning /var/run/docker.sock, or "" if it can't be determined
// (e.g. Windows/macOS Docker Desktop). The collector image runs as a hardened
// non-root uid and needs to be in the docker group to read the socket over its
// HTTP API — the value is passed to docker-compose via `group_add`.

// Up starts all services detached.
func (r *ComposeRunner) Up() error {
	removeStaleBenchContainers()
	return r.compose("up", "-d", "--quiet-pull")
}

// removeStaleBenchContainers force-removes leftover bench-* containers from a
// previous run. Container names are fixed (bench-receiver, bench-localstack,
// …), so a teardown that lost the race — or a --no-cleanup debug run — makes
// every subsequent `compose up` fail with a name conflict. Sweeping by name
// prefix right before up keeps back-to-back subject runs from tripping over
// each other's corpses.
func removeStaleBenchContainers() {
	out, err := exec.Command("docker", "ps", "-aq", "--filter", "name=^bench-").Output()
	if err != nil {
		return
	}
	ids := strings.Fields(string(out))
	if len(ids) == 0 {
		return
	}
	fmt.Printf("  removing %d stale bench container(s)…\n", len(ids))
	args := append([]string{"rm", "-f"}, ids...)
	_ = exec.Command("docker", args...).Run()
}

// UpServices starts only the named compose services.
func (r *ComposeRunner) UpServices(services ...string) error {
	resolved := r.resolveServiceAliases(services)
	args := append([]string{"up", "-d", "--quiet-pull"}, resolved...)
	return r.compose(args...)
}

// resolveServiceAliases expands the logical names "generator" and "receiver"
// to the concrete plural service names when the case uses the plural form.
// Other names are passed through unchanged. Lets existing callers like
// `UpServices("generator")` keep working even after a case adopts plural
// generators.
func (r *ComposeRunner) resolveServiceAliases(names []string) []string {
	tc := r.cfg.TestCase
	out := make([]string, 0, len(names))
	for _, n := range names {
		switch n {
		case "generator":
			if tc.MultiGenerator() {
				out = append(out, r.genServices...)
				continue
			}
		case "receiver":
			if tc.MultiReceiver() {
				out = append(out, r.recvServices...)
				continue
			}
		}
		out = append(out, n)
	}
	return out
}

// StopServices sends SIGTERM to named services with the given grace timeout
// before SIGKILL. Uses `docker compose stop -t <seconds> <svc>...`.
func (r *ComposeRunner) StopServices(timeout time.Duration, services ...string) error {
	secs := max(int(timeout.Seconds()), 0)
	resolved := r.resolveServiceAliases(services)
	args := append([]string{"stop", "-t", strconv.Itoa(secs)}, resolved...)
	return r.compose(args...)
}

// KillServices sends SIGKILL immediately — no grace period, no chance for
// the process to clean up. Mirrors a crash scenario for persistence tests.
// Uses `docker compose kill -s SIGKILL <svc>...`.
func (r *ComposeRunner) KillServices(services ...string) error {
	resolved := r.resolveServiceAliases(services)
	args := append([]string{"kill", "-s", "SIGKILL"}, resolved...)
	return r.compose(args...)
}

// Down stops and removes all containers and anonymous volumes.
func (r *ComposeRunner) Down() error {
	return r.compose("down", "-v", "--remove-orphans")
}

// WaitForGeneratorExit blocks until ALL generator containers exit or the
// timeout expires. In the singular case there's exactly one; in the plural
// case every generator must finish before the run is considered "send-
// complete". Returns the first non-zero exit code observed (if any).
func (r *ComposeRunner) WaitForGeneratorExit(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	pending := append([]string(nil), r.genContainers...)
	var firstErr error
	for time.Now().Before(deadline) {
		var still []string
		for _, name := range pending {
			out, err := exec.Command("docker", "inspect", "--format={{.State.Status}}", name).Output()
			if err != nil {
				still = append(still, name)
				continue
			}
			status := strings.TrimSpace(string(out))
			if status == "exited" {
				if cerr := r.checkExitCode(name); cerr != nil && firstErr == nil {
					firstErr = cerr
				}
				continue
			}
			still = append(still, name)
		}
		if len(still) == 0 {
			return firstErr
		}
		pending = still
		time.Sleep(2 * time.Second)
	}
	return fmt.Errorf("generator(s) did not exit within %s (still running: %v)", timeout, pending)
}

// WaitForVerifierExit blocks until the bench-verifier container exits or the
// timeout expires. A non-zero exit is NOT treated as an error here: the
// verifier exits 1 when the correctness verdict fails, which is a legitimate
// test outcome the runner reads from verdict.json — only a timeout (the
// container never finished) is an error.
func (r *ComposeRunner) WaitForVerifierExit(timeout time.Duration) error {
	const name = "bench-verifier"
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		out, err := exec.Command("docker", "inspect", "--format={{.State.Status}}", name).Output()
		if err == nil && strings.TrimSpace(string(out)) == "exited" {
			return nil
		}
		time.Sleep(2 * time.Second)
	}
	return fmt.Errorf("verifier did not exit within %s", timeout)
}

func (r *ComposeRunner) checkExitCode(container string) error {
	out, err := exec.Command("docker", "inspect", "--format={{.State.ExitCode}}", container).Output()
	if err != nil {
		return nil
	}
	code := strings.TrimSpace(string(out))
	if code != "0" {
		logs, _ := exec.Command("docker", "logs", "--tail", "50", container).CombinedOutput()
		return fmt.Errorf("%s exited with code %s:\n%s", container, code, string(logs))
	}
	return nil
}

// Logs returns the last N lines of logs for a compose service.
func (r *ComposeRunner) Logs(service string, lines int) string {
	out, err := exec.Command("docker", "compose", "-f", r.composeFile,
		"logs", "--tail", fmt.Sprintf("%d", lines), "--no-color", service).CombinedOutput()
	if err != nil {
		return fmt.Sprintf("(could not get logs: %v)", err)
	}
	return string(out)
}

// StopCollector sends SIGTERM to the collector container and waits for it to exit.
// The collector writes its CSV file on SIGTERM, so this must be called before CopyMetricsCSV.
func (r *ComposeRunner) StopCollector() error {
	// docker stop sends SIGTERM and waits up to 10s for graceful exit.
	out, err := exec.Command("docker", "stop", "-t", "10", "bench-collector").CombinedOutput()
	if err != nil {
		return fmt.Errorf("docker stop bench-collector: %w\n%s", err, out)
	}
	return nil
}

// CopyMetricsCSV copies the metrics CSV from the (stopped) collector container to dst.
// Call StopCollector first so the CSV has been flushed.
func (r *ComposeRunner) CopyMetricsCSV(dst string) error {
	src := "bench-collector:/results/metrics.csv"
	out, err := exec.Command("docker", "cp", src, dst).CombinedOutput()
	if err == nil {
		return nil
	}
	// Enrich the error when the collector crashed before writing — otherwise
	// the user just sees "Could not find the file" with no clue why.
	stateOut, _ := exec.Command("docker", "inspect",
		"--format={{.State.Status}}|{{.State.ExitCode}}|{{.State.Error}}",
		"bench-collector").Output()
	state := strings.TrimSpace(string(stateOut))
	if state != "" && !strings.HasPrefix(state, "running|") {
		logs, _ := exec.Command("docker", "logs", "--tail", "30", "bench-collector").CombinedOutput()
		return fmt.Errorf("docker cp %s → %s: %w\ncollector state: %s\ncollector logs:\n%s\ndocker cp stderr:\n%s",
			src, dst, err, state, string(logs), out)
	}
	return fmt.Errorf("docker cp %s → %s: %w\n%s", src, dst, err, out)
}

// SubjectContainer returns the container name used for the subject.
func (r *ComposeRunner) SubjectContainer() string {
	return "bench-subject-" + r.cfg.Subject.Name
}

// ReceiverMetricsPort returns the host port where the receiver's /metrics
// endpoint is exposed. In the multi-receiver case this returns the first
// receiver's port — call ReceiverMetricsPorts() instead when each receiver
// is queried individually.
func (r *ComposeRunner) ReceiverMetricsPort() (int, func(), error) {
	return r.cfg.ReceiverHostPort, func() {}, nil
}

// ReceiverMetricsPorts returns the per-receiver host port map (id → port).
// For singular-receiver cases the map has one entry under id "default".
func (r *ComposeRunner) ReceiverMetricsPorts() map[string]int {
	out := make(map[string]int, len(r.recvHostPorts))
	maps.Copy(out, r.recvHostPorts)
	return out
}

// GeneratorContainers returns the names of all generator containers used
// for this run (one in singular mode, N in plural mode). Used by the
// runner when it needs to read each generator's stdout.
func (r *ComposeRunner) GeneratorContainers() []string {
	return append([]string(nil), r.genContainers...)
}

// GeneratorStdout returns the stdout of the (singular) generator container.
// In plural-generator mode this returns the concatenation of every
// generator's stdout, separated by newlines, so callers that aggregate by
// summing fields across JSON objects still get every blob.
func (r *ComposeRunner) GeneratorStdout() string {
	if len(r.genContainers) == 1 {
		out, _ := exec.Command("docker", "logs", r.genContainers[0]).Output()
		return string(out)
	}
	var b strings.Builder
	for _, c := range r.genContainers {
		out, _ := exec.Command("docker", "logs", c).Output()
		b.Write(out)
		b.WriteString("\n")
	}
	return b.String()
}

func (r *ComposeRunner) compose(args ...string) error {
	cmdArgs := append([]string{"compose", "-f", r.composeFile}, args...)
	cmd := exec.Command("docker", cmdArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// generatorTpl is the per-generator template data when the case uses the
// plural `generators:` form.
type generatorTpl struct {
	ID            string
	Mode          string
	Target        string
	Rate          int
	TotalLines    int64
	LineSize      int
	Format        string
	Connections   int
	ConnOffset    int
	Env           map[string]string
	TLSEnabled    bool
	TLSCert       string
	TLSKey        string
	TLSCA         string
	TLSInsecure   string
	TLSMinVersion string
	// Sample-file replay (see GeneratorConfig.SampleFile). SampleFileHost is
	// the host path bind-mounted read-only at SampleFileDst; SampleFile is the
	// in-container path passed via GENERATOR_SAMPLE_FILE. Each plural generator
	// is its own container, so SampleFileDst can be the same path across them.
	SampleFile       string
	SampleFileHost   string
	SampleFileDst    string
	RewriteTimestamp bool
}

// receiverTpl is the per-receiver template data when the case uses the
// plural `receivers:` form.
type receiverTpl struct {
	ID       string
	Mode     string
	Listen   string
	HostPort int
	Env      map[string]string
	// AWSDep/AzureDep/MinioDep gate a depends_on on the emulator services —
	// set for cloud-polling receiver modes only, so listening receivers
	// start immediately as before.
	AWSDep   bool
	AzureDep bool
	MinioDep bool
}

// endpointTpl is the per-endpoint template data for the auxiliary containers
// declared via a case's `endpoints:` list.
type endpointTpl struct {
	Name    string
	Image   string
	Env     map[string]string
	Command string // pre-formatted YAML list, empty = use the image's default
}

type composeVars struct {
	SubjectImage      string
	SubjectContainer  string
	ConfigSrc         string
	ConfigDst         string
	ConfigMountOpts   string // ":ro" or ""
	TmpDir            string
	SubjectCmd        string
	SubjectEntrypoint string
	SubjectUser       string
	SubjectCertDir    string
	SubjectVaultDir   string
	SubjectEnv        map[string]string
	HasResourceLimits bool
	CPULimit          string
	MemLimit          string
	UseSharedData     bool
	DeferReceiver     bool
	// EmitGenerator gates the singular `generator:` service. False when the
	// case configures no generator (data is driven by the subject/endpoints),
	// so the template renders no generator at all.
	EmitGenerator    bool
	GeneratorImage   string
	ReceiverImage    string
	CollectorImage   string
	ReceiverHostPort int
	GenMode          string
	GenTarget        string
	GenRate          int
	GenDuration      string
	GenLineSize      int
	GenFormat        string
	GenWarmup        string
	GenSequenced     string
	GenConnections   int
	GenTotalLines    int64
	GenEnv           map[string]string
	GenRotateMode    string
	GenRotateAt      string
	GenRotateQuiesce string
	GenRotateSuffix  string
	GenTLSEnabled    bool
	GenTLSCert       string
	GenTLSKey        string
	GenTLSCA         string
	GenTLSInsecure   string
	GenTLSMinVersion string

	// Sample-file replay (singular generator only). GenSampleFileHost is the
	// host path bind-mounted read-only at GenSampleFileDst; GenSampleFile is
	// the in-container path handed to the generator via GENERATOR_SAMPLE_FILE.
	GenSampleFile       string
	GenSampleFileHost   string
	GenSampleFileDst    string
	GenRewriteTimestamp bool

	// Kafka (Redpanda) topology. KafkaEnabled gates the redpanda + redpanda-init
	// services and the generator/subject depends_on wiring. GenKafkaBatch is the
	// singular generator's records-per-message packing.
	KafkaEnabled    bool
	KafkaImage      string
	KafkaTopic      string
	KafkaPartitions int
	KafkaMemory     string
	KafkaSMP        int
	GenKafkaBatch   int

	// Kafka broker auth (a case's `kafka.auth` block). KafkaAuthEnabled gates
	// the SASL/TLS broker flags, the user bootstrap in redpanda-init, the
	// broker /certs mount, and the generator SASL/TLS env. KafkaSASLMechanism
	// is "" for the mTLS-only case. KafkaAuthMethod is the per-listener
	// authentication_method ("sasl" or "mtls_identity").
	KafkaAuthEnabled       bool
	KafkaSASLEnabled       bool
	KafkaSASLMechanism     string // plain | scram-sha-256 | scram-sha-512
	KafkaTLSEnabled        bool
	KafkaRequireClientAuth bool
	KafkaAuthMethod        string // sasl | mtls_identity
	KafkaSASLUser          string
	KafkaSASLPassword      string

	// Kafka Kerberos/GSSAPI (a case's `kafka.auth.mechanism: gssapi`). When
	// enabled the orchestrator renders an Apache Kafka (KRaft) broker + a KDC +
	// kafka-init INSTEAD of Redpanda. KrbHostDir holds the KDC-generated krb5
	// material (krb5.conf + keytabs), mounted into the kdc (rw), broker, and
	// subject (ro). KerberosInitCmd is the KDC bootstrap shell line.
	KafkaGSSAPIEnabled  bool
	KerberosRealm       string
	KerberosServiceName string
	KDCImage            string
	KrbHostDir          string
	KerberosInitCmd     string
	KafkaClusterID      string
	// KafkaBootstrapMechanism is the SCRAM mechanism redpanda-init creates the
	// user under: SCRAM-SHA-512 for the scram-sha-512 case, SCRAM-SHA-256
	// otherwise (SASL/PLAIN authenticates against a SCRAM-SHA-256 credential).
	// A Redpanda user can only be created once, so we pick the single mechanism
	// the case actually uses.
	KafkaBootstrapMechanism string

	// Vault topology. VaultEnabled gates the vault + vault-init services,
	// the subject's vault-init depends_on, and the /vault-tls subject mount.
	// VaultInitCmd is the pre-built one-shot seeding shell line: mount and
	// paths are charset-validated at case load, and the secret values live
	// in the mounted JSON files, never in this string.
	VaultEnabled     bool
	VaultImage       string
	VaultToken       string
	VaultTLSHost     string
	VaultSecretsHost string
	VaultInitCmd     string

	RecvMode              string
	RecvListen            string
	RecvEnv               map[string]string
	RecvAWSDep            bool
	RecvAzureDep          bool
	RecvMinioDep          bool
	RecvValidateDedup     string
	RecvValidateContent   string
	RecvExpectedLines     int64
	RecvRequiredSubstring string
	RecvValidateJSON      bool
	RecvRecordArrival     bool
	DockerSocketGID       string

	// Verifier (a case's `verifier:` block): a one-shot DuckDB container under
	// the compose profile "verify", so the initial Up() skips it. The runner
	// starts it via UpServices("verifier") after the generator exits, it reads
	// the subject's columnar objects from the S3 emulator via httpfs, and emits
	// /results/verdict.json. When enabled the singular receiver is not rendered.
	VerifierEnabled      bool
	VerifierImage        string
	VerifierBucket       string
	VerifierPrefix       string
	VerifierFormat       string
	VerifierExpected     int64
	VerifierAllowOverDel string
	VerifierQuietWindow  string
	VerifierTimeout      string
	VerifierMsgField     string
	VerifierNullFields   string
	VerifierEnv          map[string]string

	// Cloud emulator topology (a case's `aws:` / `azure:` blocks).
	// AWSInitHost is the host path of the rendered LocalStack init script,
	// bind-mounted into the emulator's ready.d hook directory.
	AWSEnabled          bool
	AWSImage            string
	AWSServices         string
	AWSRegion           string
	AWSInitHost         string
	AzureEnabled        bool
	AzureImage          string
	AzureConnString     string
	AzureInitContainers string

	// MinIO emulator topology (a case's `minio:` block). MinIO is
	// S3-compatible, so it reuses the s3 generator/receiver modes and the
	// AWS_* env injected into containers; only endpoint and creds differ.
	MinioEnabled      bool
	MinioImage        string
	MinioEndpoint     string
	MinioInitBuckets  string
	MinioRootUser     string
	MinioRootPassword string

	// Plural mode: when these slices are non-empty, the template emits
	// generator-<id> / receiver-<id> services and skips the singular block.
	Generators []generatorTpl
	Receivers  []receiverTpl

	// Endpoints are auxiliary containers (a case's `endpoints:` list) emitted
	// as their own services after the collector.
	Endpoints []endpointTpl

	// TLSCertsHost is the host directory holding the auto-generated cert
	// material for TLS-enabled runs. Empty when no generator opts into
	// TLS; non-empty triggers the /certs bind mount on subject and
	// generators.
	TLSCertsHost string
}

// resolveSampleHost resolves a generator's case-relative sample_file to the
// host path bind-mounted into the generator container, returning the
// forward-slashed host path and the in-container destination. It fails fast
// rather than silently skipping the mount: a missing case directory or a
// missing/non-regular file would otherwise leave GENERATOR_SAMPLE_FILE
// pointing at a path that was never mounted, so compose rendering must not
// proceed with an unresolved sample_file. sample_file is validated to be a
// safe case-relative path at config load time (see config.validateSampleFile).
func resolveSampleHost(caseDir, sampleFile string) (host, dst string, err error) {
	if caseDir == "" {
		return "", "", fmt.Errorf("sample_file %q set but case directory is empty", sampleFile)
	}
	hostPath := filepath.Join(caseDir, sampleFile)
	info, statErr := os.Stat(hostPath)
	if statErr != nil {
		return "", "", fmt.Errorf("sample_file %q: %w", sampleFile, statErr)
	}
	if !info.Mode().IsRegular() {
		return "", "", fmt.Errorf("sample_file %q is not a regular file", hostPath)
	}
	return filepath.ToSlash(hostPath), "/input/" + filepath.Base(sampleFile), nil
}

func writeCompose(path string, cfg RunConfig) error {
	tc := cfg.TestCase
	s := cfg.Subject

	// Render the subject config as a template (opt-in via {{...}}) so it can
	// adapt to the host's CPU count.
	renderedConfigSrc, err := renderSubjectConfig(cfg.ConfigSrcPath, cfg.TmpDir, configTemplateContext{
		CPUs: runtime.NumCPU(),
	})
	if err != nil {
		return err
	}

	// Docker Compose on Windows needs forward slashes in volume paths;
	// backslashes are interpreted as YAML escape sequences inside quoted strings.
	configSrc := filepath.ToSlash(renderedConfigSrc)
	tmpDir := filepath.ToSlash(cfg.TmpDir)

	subjectContainer := "bench-subject-" + s.Name

	// Cloud emulator env. Injected into the subject whenever the case
	// declares an emulator (subject configs interpolate these), and into
	// generators/receivers per-mode below. Values are public emulator
	// constants — never real credentials.
	var awsEnv, minioEnv, azureEnv map[string]string
	if tc.UsesAWS() {
		awsEnv = map[string]string{
			"AWS_ACCESS_KEY_ID":     config.AWSEmulatorAccessKey,
			"AWS_SECRET_ACCESS_KEY": config.AWSEmulatorSecretKey,
			"AWS_REGION":            tc.AWS.RegionOrDefault(),
			"AWS_DEFAULT_REGION":    tc.AWS.RegionOrDefault(),
			"AWS_ENDPOINT_URL":      tc.AWS.EndpointURL(),
			// Kill IMDS credential probing: no SDK in any container can
			// stall on or fall back to real AWS.
			"AWS_EC2_METADATA_DISABLED": "true",
		}
	}
	if tc.UsesMinio() {
		// MinIO speaks S3, so containers reach it through the same AWS_*
		// vars the S3 SDK reads — only the endpoint and credentials differ.
		minioEnv = map[string]string{
			"AWS_ACCESS_KEY_ID":         config.MinioRootUser,
			"AWS_SECRET_ACCESS_KEY":     config.MinioRootPassword,
			"AWS_REGION":                "us-east-1",
			"AWS_DEFAULT_REGION":        "us-east-1",
			"AWS_ENDPOINT_URL":          tc.Minio.EndpointURL(),
			"AWS_EC2_METADATA_DISABLED": "true",
		}
	}
	if tc.UsesAzure() {
		azureEnv = map[string]string{
			"AZURE_STORAGE_CONNECTION_STRING": tc.Azure.ConnectionString(),
		}
	}

	// Merge subject default env + cloud env + extra env from configuration.
	// Cloud env merges before ExtraSubjectEnv so a configuration can override.
	env := map[string]string{}
	maps.Copy(env, s.Env)
	maps.Copy(env, awsEnv)
	maps.Copy(env, minioEnv)
	maps.Copy(env, azureEnv)
	maps.Copy(env, cfg.ExtraSubjectEnv)

	warmup := tc.WarmupOrDefault(10 * time.Second).String()
	duration := tc.DurationOrDefault(2 * time.Minute).String()

	// File-based tests need a shared volume between generator and subject.
	useSharedData := tc.Generator.Mode == "file"
	if tc.MultiGenerator() {
		// In plural mode `tc.Generator` is unused; scan the list.
		for _, g := range tc.Generators {
			if g.Mode == "file" {
				useSharedData = true
				break
			}
		}
	}

	// When config source is a directory but ConfigPath points to a file,
	// mount to the parent directory so all files in the config dir are available.
	configDst := s.ConfigPath
	configIsDir := false
	if info, err := os.Stat(cfg.ConfigSrcPath); err == nil && info.IsDir() {
		configIsDir = true
		if ext := filepath.Ext(configDst); ext != "" {
			configDst = filepath.ToSlash(filepath.Dir(configDst))
		}
	}

	// For logstash with directory config, mount to config dir
	// (logstash.yml in that dir sets path.config to find the pipeline)
	if s.Name == "logstash" && configIsDir {
		configDst = "/usr/share/logstash/config"
	}

	// Verifier-based correctness cases (e.g. S3 Avro/Parquet) assert a unique
	// msg per source record. The generator's default json path reuses one
	// pre-generated templateLine for every record, which that assertion can
	// never satisfy — so enable sequenced (unique-per-record) generation for
	// verifier cases too, the same way receiver dedup/content checks do.
	sequenced := boolStr(tc.Correctness.ValidateDedup || tc.Correctness.ValidateContent || tc.UsesVerifier())
	tlsCertsHost := filepath.ToSlash(cfg.TLSCertsHost)

	vars := composeVars{
		SubjectImage:      s.ImageRef(),
		SubjectContainer:  subjectContainer,
		ConfigSrc:         configSrc,
		ConfigDst:         configDst,
		ConfigMountOpts:   configMountOpts(s),
		TmpDir:            tmpDir,
		SubjectCmd:        formatYAMLList(s.Command),
		SubjectEntrypoint: formatYAMLList(s.Entrypoint),
		SubjectUser:       s.User,
		SubjectCertDir:    s.CertDir,
		SubjectVaultDir:   s.VaultDir,
		SubjectEnv:        env,
		HasResourceLimits: cfg.CPULimit != "" || cfg.MemLimit != "",
		CPULimit:          defaultStr(cfg.CPULimit, "1"),
		MemLimit:          defaultStr(cfg.MemLimit, "1g"),
		UseSharedData:     useSharedData,
		// DeferReceiver drops the `generator.depends_on: receiver` link
		// so `UpServices("generator")` doesn't transitively start the
		// receiver. Needed for any test where the subject must buffer
		// or persist while the receiver is offline — without this, a
		// fast subject forwards everything in real time and the
		// restart/crash phase has nothing left to recover.
		DeferReceiver: tc.Type == "persistence_correctness" ||
			tc.Type == "persistence_restart_correctness" ||
			tc.Type == "persistence_crash_correctness",
		GeneratorImage:   cfg.GeneratorImage,
		ReceiverImage:    cfg.ReceiverImage,
		CollectorImage:   cfg.CollectorImage,
		ReceiverHostPort: cfg.ReceiverHostPort,
		GenDuration:      duration,
		GenWarmup:        warmup,
		// Sequenced lines (CONN=<id> SEQ=<n> ...) are only needed when the
		// receiver runs a check that requires per-line uniqueness or a
		// known prefix structure — dedup or content validation. The
		// previous blanket "type == correctness" rule forced sequenced
		// data into tests like wrapped_json_correctness whose generator
		// format is "json"; those lines started with CONN= instead of {,
		// silently failing JSON-parsing subjects (e.g. AxoSyslog).
		GenSequenced:    sequenced,
		DockerSocketGID: cfg.DockerSocketGID,
		TLSCertsHost:    tlsCertsHost,

		RecvValidateDedup:     boolStr(tc.Correctness.ValidateDedup),
		RecvValidateContent:   boolStr(tc.Correctness.ValidateContent),
		RecvExpectedLines:     0,
		RecvRequiredSubstring: tc.Correctness.RequiredSubstring,
		RecvValidateJSON:      tc.Correctness.ValidateJSON,
		// Arrival timestamp recording is opt-in via the rate_ceiling
		// check; flipping it on unconditionally would burn memory in
		// every performance run.
		RecvRecordArrival: tc.Correctness.RateCeiling.Enabled(),
	}

	if tc.MultiGenerator() {
		offset := 0
		for _, g := range tc.Generators {
			conns := resolveGeneratorConnections(g.Connections)
			lineSize := g.LineSize
			if lineSize == 0 {
				lineSize = 256
			}
			format := g.Format
			if format == "" {
				format = "raw"
			}
			// Sample-file replay (same wiring as the singular path).
			sampleFile, sampleHost, sampleDst := "", "", ""
			if g.SampleFile != "" {
				host, dst, err := resolveSampleHost(cfg.CaseDir, g.SampleFile)
				if err != nil {
					return err
				}
				sampleHost = host
				sampleDst = dst
				sampleFile = dst
			}
			vars.Generators = append(vars.Generators, generatorTpl{
				ID:               g.ID,
				Mode:             g.Mode,
				Target:           g.Target,
				Rate:             g.Rate,
				TotalLines:       g.TotalLines,
				LineSize:         lineSize,
				Format:           format,
				Connections:      conns,
				ConnOffset:       offset,
				Env:              mergeEnv(cloudEnvForMode(g.Mode, awsEnv, minioEnv, azureEnv), g.Env),
				TLSEnabled:       g.TLS.Enabled,
				TLSCert:          g.TLS.Cert,
				TLSKey:           g.TLS.Key,
				TLSCA:            g.TLS.CA,
				TLSInsecure:      boolStr(g.TLS.InsecureSkipVerify),
				TLSMinVersion:    g.TLS.MinVersion,
				SampleFile:       sampleFile,
				SampleFileHost:   sampleHost,
				SampleFileDst:    sampleDst,
				RewriteTimestamp: g.RewriteTimestamp,
			})
			offset += conns
		}
	} else {
		g := tc.Generator
		vars.EmitGenerator = g.Mode != "" || g.Target != ""
		genLineSize := g.LineSize
		if genLineSize == 0 {
			genLineSize = 256
		}
		genFormat := g.Format
		if genFormat == "" {
			genFormat = "raw"
		}
		vars.GenMode = g.Mode
		vars.GenTarget = g.Target
		vars.GenRate = g.Rate
		vars.GenLineSize = genLineSize
		vars.GenFormat = genFormat
		vars.GenConnections = resolveGeneratorConnections(g.Connections)
		vars.GenTotalLines = g.TotalLines
		vars.GenEnv = mergeEnv(cloudEnvForMode(g.Mode, awsEnv, minioEnv, azureEnv), g.Env)
		vars.GenRotateMode = g.FileRotation.Mode
		vars.GenRotateAt = g.FileRotation.At
		vars.GenRotateQuiesce = g.FileRotation.Quiesce
		vars.GenRotateSuffix = g.FileRotation.ArchiveSuffix
		vars.GenTLSEnabled = g.TLS.Enabled
		vars.GenTLSCert = g.TLS.Cert
		vars.GenTLSKey = g.TLS.Key
		vars.GenTLSCA = g.TLS.CA
		vars.GenTLSInsecure = boolStr(g.TLS.InsecureSkipVerify)
		vars.GenTLSMinVersion = g.TLS.MinVersion

		// Sample-file replay: bind-mount the case's input file into the
		// generator and point GENERATOR_SAMPLE_FILE at it. Path in case.yaml
		// is relative to the case directory.
		if g.SampleFile != "" {
			host, dst, err := resolveSampleHost(cfg.CaseDir, g.SampleFile)
			if err != nil {
				return err
			}
			vars.GenSampleFileHost = host
			vars.GenSampleFileDst = dst
			vars.GenSampleFile = dst
			vars.GenRewriteTimestamp = g.RewriteTimestamp
		}
		vars.GenKafkaBatch = max(g.KafkaBatch, 1)
	}

	// Kafka (Redpanda) broker: render the redpanda + redpanda-init services and
	// wire the generator/subject depends_on. Defaults centralized on KafkaConfig.
	if tc.Kafka != nil {
		vars.KafkaEnabled = true
		vars.KafkaImage = tc.Kafka.KafkaImageOrDefault()
		vars.KafkaTopic = tc.Kafka.TopicOrDefault()
		vars.KafkaPartitions = tc.Kafka.PartitionsOrDefault()
		vars.KafkaMemory = tc.Kafka.MemoryOrDefault()
		vars.KafkaSMP = tc.Kafka.SMPOrDefault()

		// Broker auth (`kafka.auth`). SASL users are bootstrapped by
		// redpanda-init over the (unauthenticated) admin API; topics
		// auto-create on first produce so no authenticated topic-init is
		// needed. The broker /certs mount and the generator's SASL/TLS env are
		// gated on these too. The director reads the password from
		// KAFKA_SASL_PASSWORD (the case configs reference ${KAFKA_SASL_PASSWORD}).
		if tc.Kafka.AuthEnabled() {
			vars.KafkaAuthEnabled = true
			vars.KafkaSASLEnabled = tc.Kafka.UsesSASL()
			vars.KafkaSASLMechanism = tc.Kafka.SASLMechanism()
			vars.KafkaTLSEnabled = tc.Kafka.UsesTLS()
			vars.KafkaRequireClientAuth = tc.Kafka.RequireClientAuth()
			vars.KafkaSASLUser = config.KafkaSASLUser
			vars.KafkaSASLPassword = config.KafkaSASLPassword
			if tc.Kafka.UsesSASL() {
				vars.KafkaAuthMethod = "sasl"
				if tc.Kafka.SASLMechanism() == "scram-sha-512" {
					vars.KafkaBootstrapMechanism = "SCRAM-SHA-512"
				} else {
					// plain + scram-sha-256 both authenticate against a
					// SCRAM-SHA-256 credential.
					vars.KafkaBootstrapMechanism = "SCRAM-SHA-256"
				}
				env["KAFKA_SASL_PASSWORD"] = config.KafkaSASLPassword
			} else {
				// mTLS-only: the client certificate carries the principal.
				vars.KafkaAuthMethod = "mtls_identity"
			}
		}

		// Kerberos/GSSAPI: render an Apache Kafka (KRaft) broker + KDC instead
		// of Redpanda (which gates Kerberos behind an enterprise license). The
		// krb5 dir + bootstrap command are provisioned by PrepareKerberos in
		// NewComposeRunner (same pattern as Vault).
		if tc.Kafka.UsesGSSAPI() {
			// NewComposeRunner populates these from PrepareKerberos; a direct
			// writeCompose caller that skips that would otherwise render an
			// invalid /krb5 mount and an empty KDC command. Fail fast instead.
			if cfg.KrbHostDir == "" || strings.TrimSpace(cfg.KerberosInitCmd) == "" {
				return fmt.Errorf("case %q uses kafka gssapi but kerberos topology is incomplete (krb host dir/init cmd)", tc.Name)
			}
			vars.KafkaGSSAPIEnabled = true
			vars.KerberosRealm = tc.Kafka.RealmOrDefault()
			vars.KerberosServiceName = tc.Kafka.ServiceNameOrDefault()
			vars.KDCImage = "vmetric/bench-kdc:latest"
			vars.KrbHostDir = filepath.ToSlash(cfg.KrbHostDir)
			vars.KerberosInitCmd = cfg.KerberosInitCmd
			// Fixed valid KRaft cluster id — the per-run broker is throwaway.
			vars.KafkaClusterID = "MkU3OEVBNTcwNTJENDM2Qk"
			// The Kerberos case needs a GSSAPI-capable broker; if the case
			// didn't pin one, default to cp-kafka (Redpanda can't serve it).
			if tc.Kafka.Image == "" {
				vars.KafkaImage = "confluentinc/cp-kafka:7.7.1"
			}
		}
	}

	// Vault dev server: render the vault + vault-init services and gate the
	// subject on the seeding completing. Defaults centralized on VaultConfig.
	if tc.UsesVault() {
		if cfg.VaultTLSHost == "" || cfg.VaultSecretsHost == "" {
			return fmt.Errorf("case %q uses vault but the vault host dirs were not prepared", tc.Name)
		}
		vars.VaultEnabled = true
		vars.VaultImage = tc.Vault.VaultImageOrDefault()
		vars.VaultToken = tc.Vault.TokenOrDefault()
		vars.VaultTLSHost = filepath.ToSlash(cfg.VaultTLSHost)
		vars.VaultSecretsHost = filepath.ToSlash(cfg.VaultSecretsHost)
		var sb strings.Builder
		sb.WriteString("set -e; ")
		for _, s := range cfg.VaultSeeds {
			fmt.Fprintf(&sb, "vault kv put -mount=%s %s @/vault-secrets/%s; ",
				tc.Vault.MountOrDefault(), s.Path, s.File)
		}
		sb.WriteString("echo vault seeding complete")
		vars.VaultInitCmd = sb.String()
	}

	if tc.MultiReceiver() {
		for i, rc := range tc.Receivers {
			vars.Receivers = append(vars.Receivers, receiverTpl{
				ID:       rc.ID,
				Mode:     rc.Mode,
				Listen:   rc.Listen,
				HostPort: cfg.ReceiverHostPort + i,
				Env:      mergeEnv(cloudEnvForMode(rc.Mode, awsEnv, minioEnv, azureEnv), rc.Env),
				AWSDep:   tc.UsesAWS() && config.IsCloudPollingReceiverMode(rc.Mode) && rc.Mode != "azure_blob",
				AzureDep: tc.UsesAzure() && rc.Mode == "azure_blob",
				MinioDep: tc.UsesMinio() && rc.Mode == "s3",
			})
		}
	} else {
		vars.RecvMode = tc.Receiver.Mode
		vars.RecvListen = tc.Receiver.Listen
		vars.RecvEnv = mergeEnv(cloudEnvForMode(tc.Receiver.Mode, awsEnv, minioEnv, azureEnv), tc.Receiver.Env)
		vars.RecvAWSDep = tc.UsesAWS() && config.IsCloudPollingReceiverMode(tc.Receiver.Mode) && tc.Receiver.Mode != "azure_blob"
		vars.RecvAzureDep = tc.UsesAzure() && tc.Receiver.Mode == "azure_blob"
		vars.RecvMinioDep = tc.UsesMinio() && tc.Receiver.Mode == "s3"
	}

	// Cloud emulator services. The AWS init script is rendered from the
	// validated `aws:` block and bind-mounted into LocalStack's ready.d
	// hook directory; the healthcheck gates on it completing.
	if tc.UsesAWS() {
		vars.AWSEnabled = true
		vars.AWSImage = tc.AWS.ImageOrDefault()
		vars.AWSServices = tc.AWS.ServicesOrDefault()
		vars.AWSRegion = tc.AWS.RegionOrDefault()
		initPath := filepath.Join(cfg.TmpDir, "aws-init.sh")
		if err := writeAWSInit(initPath, tc.AWS); err != nil {
			return err
		}
		vars.AWSInitHost = filepath.ToSlash(initPath)
	}
	if tc.UsesAzure() {
		vars.AzureEnabled = true
		vars.AzureImage = tc.Azure.ImageOrDefault()
		vars.AzureConnString = tc.Azure.ConnectionString()
		vars.AzureInitContainers = strings.Join(tc.Azure.Containers, ",")
	}
	if tc.UsesMinio() {
		vars.MinioEnabled = true
		vars.MinioImage = tc.Minio.ImageOrDefault()
		vars.MinioEndpoint = tc.Minio.EndpointURL()
		vars.MinioInitBuckets = strings.Join(tc.Minio.Buckets, ",")
		vars.MinioRootUser = config.MinioRootUser
		vars.MinioRootPassword = config.MinioRootPassword
	}

	// Verifier: a one-shot DuckDB container that reads the subject's columnar
	// objects from the S3 emulator. EXPECTED_LINES comes from the case's fixed
	// generator total_lines (deterministic — a rate-limited generator with
	// total_lines set sends exactly that many), so the verifier can assert an
	// exact count without a runtime handoff. S3 access reuses the emulator's
	// credential/endpoint env.
	if tc.UsesVerifier() {
		vars.VerifierEnabled = true
		vars.VerifierImage = cfg.VerifierImage
		vars.VerifierBucket = tc.Verifier.S3Bucket
		vars.VerifierPrefix = tc.Verifier.S3Prefix
		vars.VerifierFormat = tc.Verifier.Format
		vars.VerifierExpected = tc.Generator.TotalLines
		vars.VerifierAllowOverDel = boolStr(tc.Verifier.AllowOverDelivery)
		vars.VerifierQuietWindow = tc.Verifier.QuietWindowOrDefault()
		vars.VerifierTimeout = tc.Verifier.TimeoutOrDefault()
		vars.VerifierMsgField = defaultStr(tc.Verifier.MsgField, "msg")
		vars.VerifierNullFields = strings.Join(tc.Verifier.NullFields, ",")
		if tc.UsesMinio() {
			vars.VerifierEnv = minioEnv
		} else {
			vars.VerifierEnv = awsEnv
		}
	}

	for _, ep := range tc.Endpoints {
		// Compose interpolates "$" in the compose file ($VAR, ${VAR}, $(...)),
		// which would corrupt an endpoint's inline shell command. Escape "$" to
		// "$$" so compose passes a literal "$" through to the container shell —
		// case authors write normal shell ($(date), ${VAR}) and it Just Works.
		cmd := make([]string, len(ep.Command))
		for i, c := range ep.Command {
			cmd[i] = strings.ReplaceAll(c, "$", "$$")
		}
		env := map[string]string{}
		for k, v := range ep.Env {
			env[k] = strings.ReplaceAll(v, "$", "$$")
		}
		vars.Endpoints = append(vars.Endpoints, endpointTpl{
			Name:    ep.Name,
			Image:   ep.Image,
			Env:     env,
			Command: formatYAMLList(cmd),
		})
	}

	tmpl, err := template.New("compose").Parse(composeTemplate)
	if err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, vars)
}

// formatYAMLList formats a string slice as a YAML inline list: ["a", "b", "c"]
func formatYAMLList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func configMountOpts(s config.Subject) string {
	if s.ConfigRW {
		return ""
	}
	return ":ro"
}

func defaultStr(val, def string) string {
	if val != "" {
		return val
	}
	return def
}

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}
