[SERVICE]
    Flush        1
    Log_Level    warn

[INPUT]
    Name         tcp
    Listen       0.0.0.0
    Port         9000
    Format       none
    Chunk_Size   256k
    Buffer_Size  512k

[OUTPUT]
    Name         kinesis_streams
    Match        *
    stream       bench-stream
    region       us-east-1
    endpoint     http://localstack:4566
    log_key      log
