devices:
  - id: 1
    name: tcp-bench
    type: tcp
    properties:
      address: "0.0.0.0"
      port: 9000
targets:
  - name: sqs-target-bench
    type: amazonsqs
    properties:
      endpoint: "http://localstack:4566"
      key: "test"
      secret: "test"
      region: "us-east-1"
      queue: "bench-out"
routes:
  - name: tcp-to-sqs-bench
    devices:
      - name: tcp-bench
    targets:
      - name: sqs-target-bench
