input {
  tcp {
    port => 9000
    codec => line
  }
}

filter {
  mutate {
    gsub => [ "message", "CONN=\d+", "CONN=***" ]
  }
}

output {
  tcp {
    host => "receiver"
    port => 9001
    codec => line
  }
}
