tenzir:
  pipelines:
    tcp-to-tcp-mask:
      name: TCP regex mask to TCP
      restart-on-error: 5 seconds
      definition: |
        load_tcp "0.0.0.0:9000"
        read_lines
        this.line = this.line.replace(r"CONN=\d+", "CONN=***")
        write_lines
        save_tcp "receiver:9001"
