input {
  tcp {
    port => 9000
    codec => line
  }
}

output {
  http {
    url => "http://receiver:9001/"
    http_method => "post"
    format => "message"
    message => "%{message}"
    content_type => "text/plain"
    pool_max => 4
    pool_max_per_route => 4
  }
}
