input {
  tcp {
    port => 9000
    codec => line
  }
}

output {
  s3 {
    bucket => "bench-out"
    region => "us-east-1"
    endpoint => "http://localstack:4566"
    additional_settings => { "force_path_style" => "true" }
    size_file => 5242880
    time_file => 0.05
    rotation_strategy => "size_and_time"
    temporary_directory => "/tmp/logstash-s3"
    validate_credentials_on_root_bucket => false
    codec => line { format => "%{message}" }
  }
}
