[sources.in]
type = "socket"
mode = "tcp"
address = "0.0.0.0:9000"
decoding.codec = "bytes"
framing.method = "newline_delimited"

[sinks.out]
type = "aws_s3"
inputs = ["in"]
bucket = "bench-out"
key_prefix = "vector/"
endpoint = "http://localstack:4566"
force_path_style = true

[sinks.out.encoding]
codec = "text"