devices:
  - id: 1
    name: tcp-bench
    type: tcp
    properties:
      address: "0.0.0.0"
      port: 9000
targets:
  - name: s3-target-bench
    type: awss3
    properties:
      endpoint: "http://localstack:4566"
      bucket: "bench-out"
      format: raw
      compression: gzip
      extension: log.gz
routes:
  - name: tcp-to-s3-bench
    devices:
      - name: tcp-bench
    targets:
      - name: s3-target-bench
