@version: 4.2

source s_tcp {
    tcp(
        ip("0.0.0.0")
        port(9000)
        flags(syslog-protocol)
    );
};

filter f_not_debug {
    level(info..emerg);
};

destination d_tcp {
    tcp(
        "receiver"
        port(9001)
    );
};

log {
    source(s_tcp);
    filter(f_not_debug);
    destination(d_tcp);
};
