id: real_world
conf:
  output: default
  groups: {}
  asyncFuncTimeout: 1000
  functions:
    - id: eval
      filter: "Number(severity) === 7"
      disabled: false
      conf:
        add:
          - name: dropped
            value: "true"
