id: real_world
conf:
  output: default
  groups: {}
  asyncFuncTimeout: 1000
  functions:
    - id: parser
      filter: "true"
      disabled: false
      conf:
        mode: extract
        type: regex
        srcField: _raw
        regex: "/<(?<priority>\\d+)>(?<timestamp>\\S+) (?<host>\\S+) (?<program>\\S+?)(?:\\[(?<pid>\\d+)\\])?: (?<msg>.*)/"
    - id: eval
      filter: "priority && (Number(priority) % 8) === 7"
      disabled: false
      conf:
        add:
          - name: dropped
            value: "true"
