[SERVICE]
    Flush        1
    Log_Level    warn

[INPUT]
    Name         tcp
    Listen       0.0.0.0
    Port         9000
    Format       none
    Chunk_Size   256k
    Buffer_Size  512k

[OUTPUT]
    Name                  azure_blob
    Match                 *
    account_name          devstoreaccount1
    shared_key            Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    endpoint              http://azurite:10000
    container_name        bench-out
    auto_create_container on
    blob_type             blockblob
