[SERVICE]
    Flush        1
    Log_Level    warn

[INPUT]
    Name         tcp
    Listen       0.0.0.0
    Port         9000
    Format       none
    Chunk_Size   256k
    Buffer_Size  512k

[OUTPUT]
    Name              s3
    Match             *
    bucket            bench-out
    region            us-east-1
    endpoint          http://minio:9000
    use_put_object    On
    total_file_size   5M
    upload_timeout    5s
    store_dir         /tmp/fb-s3
    log_key           log
