receivers:
  tcplog:
    listen_address: "0.0.0.0:9000"

exporters:
  syslog:
    endpoint: "receiver"
    port: 9001
    network: "tcp"
    protocol: "rfc3164"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [tcplog]
      exporters: [syslog]
