filebeat.inputs:
  - type: tcp
    host: "0.0.0.0:9000"
    max_message_size: 10KiB

output.elasticsearch:
  hosts: ["http://receiver:9002"]
  allow_older_versions: true
  compression_level: 0

logging.level: warning
queue.mem:
  events: 4096
  flush.min_events: 2048
  flush.timeout: 1s
