@version: 4.2

source s_tcp {
    tcp(
        ip("0.0.0.0")
        port(9000)
        flags(no-parse)
    );
};

destination d_http {
    http(
        url("http://receiver:9001/")
        method("POST")
        body("${MESSAGE}\n")
        workers(4)
        batch-lines(1000)
        batch-timeout(100)
        disk-buffer(
            reliable(yes)
            capacity-bytes(4294967296)
            dir("/var/lib/syslog-ng/disk-buffer/")
        )
    );
};

log {
    source(s_tcp);
    destination(d_http);
};
