@version: 4.2

source s_tcp {
    tcp(
        ip("0.0.0.0")
        port(9000)
        flags(no-parse)
    );
};

parser p_json {
    json-parser(prefix(".json."));
};

destination d_tcp {
    tcp(
        "receiver"
        port(9001)
        template("$(format-json .json.*)\n")
    );
};

log {
    source(s_tcp);
    parser(p_json);
    destination(d_tcp);
};
