tenzir:
  pipelines:
    tcp-to-tcp-json:
      name: TCP wrapped-json parse to TCP
      restart-on-error: 5 seconds
      definition: |
        load_tcp "0.0.0.0:9000"
        read_json
        write_json
        save_tcp "receiver:9001"
