[SERVICE]
    Flush        1
    Log_Level    warn
    storage.path /tmp/flb-storage/
    storage.sync normal

[INPUT]
    Name         tcp
    Listen       0.0.0.0
    Port         9000
    Format       none
    storage.type filesystem

[OUTPUT]
    Name         tcp
    Match        *
    Host         receiver
    Port         9001
    Format       json_lines
    storage.total_limit_size 1G
