[SERVICE]
    Flush        1
    Log_Level    warn

[INPUT]
    Name         tcp
    Listen       0.0.0.0
    Port         9000
    Format       none
    Chunk_Size   256k
    Buffer_Size  512k

[OUTPUT]
    Name         http
    Match        *
    Host         receiver
    Port         9001
    URI          /
    Format       json_lines
