id: default
groups: {}
comments: []
routes:
  - id: bench_route
    name: bench_passthru
    final: true
    disabled: false
    pipeline: passthru
    filter: "true"
    output: bench_http_out
    description: "Route all data through passthru to output"
