devices:
  - id: 1
    name: azblob-bench
    type: azblob
    properties:
      connection_string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;"
      container_name: "bench-in"
targets:
  - name: tcp-target-bench
    type: tcp
    properties:
      address: "receiver"
      port: 9001
routes:
  - name: azblob-to-tcp-bench
    devices:
      - name: azblob-bench
    targets:
      - name: tcp-target-bench
