input {
  file {
    path => "/data/*.log"
    start_position => "beginning"
    sincedb_path => "/tmp/logstash-sincedb"
    codec => line
  }
}

output {
  tcp {
    host => "receiver"
    port => 9001
    codec => line { format => "%{message}" }
  }
}
