inputs:
  bench_file_in:
    type: file_monitor
    disabled: false
    path: /data
    filenameExpr: "/input\\.log$/"
    mode: oldest
    pqEnabled: false
    preprocess:
      disabled: true
    sendToRoutes: true
    stateStore:
      location: state/bench_file_in
