devices:
  - id: 1
    name: s3-bench
    type: awss3
    properties:
      endpoint: "http://localstack:4566"
      use_path_style: true
      region: "us-east-1"
      access_key_id: "test"
      secret_access_key: "test"
      bucket_name: "bench-in"
      queue_url: "http://localstack:4566/000000000000/bench-events"
      file_name_filter: ".*"
      sqs_max_messages: 10
      sqs_wait_time_seconds: 2
targets:
  - name: tcp-target-bench
    type: tcp
    properties:
      address: "receiver"
      port: 9001
routes:
  - name: s3-to-tcp-bench
    devices:
      - name: s3-bench
    targets:
      - name: tcp-target-bench
