@version: 4.2

source s_file {
    wildcard-file(
        base-dir("/data")
        filename-pattern("*.log")
        flags(no-parse)
        follow-freq(0.1)
    );
};

destination d_tcp {
    tcp(
        "receiver"
        port(9001)
    );
};

log {
    source(s_file);
    destination(d_tcp);
};
