outputs:
  default:
    defaultId: bench_http_out
    type: default
  bench_http_out:
    type: webhook
    url: "http://receiver:9001/"
    method: POST
    format: ndjson
    compression: none
    concurrency: 4
    maxPayloadSizeKB: 2048
    tls:
      disabled: true
