inputs:
  bench_syslog_in:
    type: syslog
    host: 0.0.0.0
    tcpPort: 9000
    disabled: false
    maxBufferSize: 1000
    ipWhitelistRegex: /.*/
    timestampTimezone: local
    singleMsgUdpPackets: false
    enableProxyHeader: false
    keepFieldsList: []
    tls:
      disabled: true
    sendToRoutes: true
    pqEnabled: false
