input {
  tcp {
    port => 9000
    codec => line
  }
}

filter {
  grok {
    match => { "message" => "<%{POSINT:priority}>%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:host} %{PROG:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:msg}" }
  }
}

output {
  tcp {
    host => "receiver"
    port => 9001
    codec => line { format => "%{message}" }
  }
}
