tenzir:
  pipelines:
    tcp-to-tcp-syslog:
      name: TCP syslog parse to TCP
      restart-on-error: 5 seconds
      definition: |
        load_tcp "0.0.0.0:9000"
        read_syslog
        write_syslog
        save_tcp "receiver:9001"
