[SERVICE]
    Flush        1
    Log_Level    warn

[INPUT]
    Name         tcp
    Listen       0.0.0.0
    Port         9000
    Format       none

[FILTER]
    Name         lua
    Match        *
    script       /fluent-bit/scripts/passthrough.lua
    call         cb_filter

[OUTPUT]
    Name         tcp
    Match        *
    Host         receiver
    Port         9001
    Format       json_lines
