devices:
  - id: 1
    name: kafka-bench
    type: kafka
    properties:
      address: "redpanda"
      port: 9092
      topic: "bench"
      group: "bench"
targets:
  - name: tcp-target-bench
    type: tcp
    properties:
      address: "receiver"
      port: 9001
routes:
  - name: kafka-to-tcp-bench
    devices:
      - name: kafka-bench
    targets:
      - name: tcp-target-bench
